[project]
name = "trying-pixi"
version = "0.1.0"
description = "Add a short description here"
authors = ["kolibril13 <44469195+kolibril13@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = "3.11.4.*"
